In [1]:
from state_of_the_art.image_processing.image_feeddback_table import ImageFeedbackTable



df = ImageFeedbackTable().read(recent_first=True)
df

Events config given:  {'arxiv_papers': {'prevent_duplicates_col': 'abstract_url'}}

,paper_id,image_position,score,tdw_timestamp,tdw_uuid
0,2504.16923,21,0,2025-04-27 06:59:19.592210,5178ee3e-b597-4544-ac04-3b7f869b0933
0,2504.16930,33,0,2025-04-27 06:39:23.831915,490b561d-9ebe-429b-83e9-a7c250138157
0,2504.16930,31,0,2025-04-27 06:38:58.762098,f8c40042-6e95-4929-9429-c9f7f455359e
0,2504.16930,23,0,2025-04-27 06:38:58.613145,7f39d3ef-1254-4381-8da0-0d7995d1b755
0,2504.16930,5,0,2025-04-27 06:36:00.863649,607e67b1-1c69-4628-a4c4-1fb37f66397d
...,...,...,...,...,...
0,2504.02671,1,2,2025-04-11 21:13:50.048339,0169009c-3fe9-4d30-8f50-9cfd41feb160
0,2504.02660,1,2,2025-04-11 21:13:35.194911,d69d3f21-a30e-43bc-91c9-567f0618aaf1
0,2504.02660,8,2,2025-04-11 00:33:55.591658,d665817a-2cb1-4071-ac48-3bd2bde02d6e
0,2504.02660,3,2,2025-04-11 00:33:25.319904,cb3c2757-1a9b-4310-8b12-455fcdb64d0b
0,2504.02660,9,2,2025-04-11 00:22:00.028461,5794045c-8f87-4da1-a7b5-f78bde33068e

In [14]:
# cleanup image position
# it comes in the format of a path path/to/image/1.png 
# or with the image filename only 1.png
# i want only the number
df['image_position'] = df['image_position'].str.split('/').str[-1].str.split('.').str[0]
df['image_position']
df['image_position'].value_counts()

image_position
1      132
10      75
13      54
11      46
12      43
14      32
15      26
101     24
100     23
2       16
3       15
102     13
4       11
104     10
103      9
16       3
8        3
23       2
31       2
21       1
22       1
5        1
33       1
9        1
Name: count, dtype: int64

In [21]:
df[['paper_id', 'image_position', 'score']].value_counts()

paper_id    image_position  score
2504.16930  10              0        28
            11              0        26
            13              0        22
            1               0        22
2504.16929  1               0        19
                                     ..
2504.02828  104             0         1
2504.13166  3               2         1
2504.13173  2               2         1
2504.13181  101             1         1
2504.16930  8               0         1
Name: count, Length: 91, dtype: int64

In [29]:
# filter by paper id and image position and score in a single line 

df[(df['paper_id'] == '2504.16930') & (df['image_position'] == '10') ]


df = df.drop_duplicates(subset=['paper_id', 'score', 'image_position'], keep='last')
df

,paper_id,image_position,score,tdw_timestamp,tdw_uuid
0,2504.16930,33,0,2025-04-27 06:39:23.831915,490b561d-9ebe-429b-83e9-a7c250138157
0,2504.16930,31,0,2025-04-27 06:38:58.762098,f8c40042-6e95-4929-9429-c9f7f455359e
0,2504.16930,23,0,2025-04-27 06:38:58.613145,7f39d3ef-1254-4381-8da0-0d7995d1b755
0,2504.16930,5,0,2025-04-27 06:36:00.863649,607e67b1-1c69-4628-a4c4-1fb37f66397d
0,2504.16930,8,0,2025-04-27 06:34:26.887645,97bbcd04-2967-493e-8bfe-94146026f1e0
...,...,...,...,...,...
0,2504.02671,1,2,2025-04-11 21:13:50.048339,0169009c-3fe9-4d30-8f50-9cfd41feb160
0,2504.02660,1,2,2025-04-11 21:13:35.194911,d69d3f21-a30e-43bc-91c9-567f0618aaf1
0,2504.02660,8,2,2025-04-11 00:33:55.591658,d665817a-2cb1-4071-ac48-3bd2bde02d6e
0,2504.02660,3,2,2025-04-11 00:33:25.319904,cb3c2757-1a9b-4310-8b12-455fcdb64d0b
0,2504.02660,9,2,2025-04-11 00:22:00.028461,5794045c-8f87-4da1-a7b5-f78bde33068e

In [30]:
ImageFeedbackTable().replace(df, dry_run=False)

In [11]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

df['image_position'].value_counts()

image_position
1.png                                                                                                                                           62
1.jpg                                                                                                                                           58
13.jpg                                                                                                                                          52
10.jpg                                                                                                                                          44
11.jpg                                                                                                                                          30
12.jpg                                                                                                                                          27
14.jpg                                                                                                                                          23
100.jp2                                                                                                                                         22
10.jp2                                                                                                                                          22
15.jpg                                                                                                                                          16
2.png                                                                                                                                           15
12.jp2                                                                                                                                          14
101.jp2                                                                                                                                         13
3.png                                                                                                                                           13
11.png                                                                                                                                          12
4.png                                                                                                                                           10
14.png                                                                                                                                           9
101.png                                                                                                                                          8
102.jp2                                                                                                                                          7
1.jp2                                                                                                                                            6
15.png                                                                                                                                           6
102.jpg                                                                                                                                          6
103.png                                                                                                                                          6
104.png                                                                                                                                          5
104.jpg                                                                                                                                          5
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/11.jpg     4
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/15.png     4
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/10.jpg     4
1                                                                                                                                                4
10.png                                                                                                                                           4
101.jpg                                                                                                                                          3
103.jpg                                                                                                                                          3
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/16.jpg     3
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/23.jpg     2
8                                                                                                                                                2
3                                                                                                                                                2
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/31.png     2
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/1.jpg      2
2                                                                                                                                                1
100.jpg                                                                                                                                          1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/33.jpg     1
12.png                                                                                                                                           1
13.png                                                                                                                                           1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/21.jpg     1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/22.jpg     1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/4.jpg      1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/12.jpg     1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/8.jpg      1
/Users/jean.machado@getyourguide.com/prj/state-of-the-art-with-ai/state_of_the_art/image_processing/notebooks/paper_images/2504.16930/5.jpg      1
9                                                                                                                                                1
Name: count, dtype: int64

In [ ]:
ImageFeedbackTable().add_feedback(paper_id="2504.02660", image_position="9", score=5)

In [6]:
from state_of_the_art.image_processing.image_feeddback_table import ImageFeedbackTable
result = ImageFeedbackTable().get_image_score(paper_id="2504.02660", image_position="9") 

print(result)

2